# Generated by Django 3.0.7 on 2021-02-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_remove_user_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_joining_date', models.DateField(null=True)),
                ('employee_department', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_phone', models.CharField(max_length=100)),
                ('employee_created_date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
