# Generated by Django 3.0.7 on 2021-02-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_is_admin'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default='Employee', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
