# Generated by Django 3.0.7 on 2021-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210208_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_username',
        ),
    ]
